export {default as smallLanding} from './res/topper-img.png'
export {default as bigLanding} from './Intersection-1.png'
export {default as LogoDark} from './logo-dark.png'
export {default as LogoLight} from './logo-light.png'
export {default as burger} from './boorger.png'
export {default as truck} from './clipart777198.png'
export {default as screw} from './customize.png'
export {default as clock} from './iconfinder_10_171505.png'
export {default as doritos} from './58718a3c7b7f6103e35c6ce2.png'
export {default as paypal} from './580b57fcd9996e24bc43c530.png'
export {default as github} from './GitHub_Logo.png'
export {default as mainTv} from './FAVPNG_led-backlit-lcd-high-definition-television-720p-1080p_QnLiNSxr.png'
export {default as lightBlueTv} from './television-tv-png-22246.png'
export {default as blueTv} from './television-tv-png-22253.png'
export {default as orangeWaveFacingDown} from './wave.png'
export {default as glimpseTop} from './Group 18.png'
